// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: valve.shared.proto

package shared

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ValveStatus int32

const (
	ValveStatus_VALVE_UNSPECIFIED ValveStatus = 0
	ValveStatus_VALVE_INVALID     ValveStatus = 1
	ValveStatus_VALVE_OPENING     ValveStatus = 2
	ValveStatus_VALVE_OPEN        ValveStatus = 3
	ValveStatus_VALVE_CLOSING     ValveStatus = 4
	ValveStatus_VALVE_CLOSE       ValveStatus = 5
)

// Enum value maps for ValveStatus.
var (
	ValveStatus_name = map[int32]string{
		0: "VALVE_UNSPECIFIED",
		1: "VALVE_INVALID",
		2: "VALVE_OPENING",
		3: "VALVE_OPEN",
		4: "VALVE_CLOSING",
		5: "VALVE_CLOSE",
	}
	ValveStatus_value = map[string]int32{
		"VALVE_UNSPECIFIED": 0,
		"VALVE_INVALID":     1,
		"VALVE_OPENING":     2,
		"VALVE_OPEN":        3,
		"VALVE_CLOSING":     4,
		"VALVE_CLOSE":       5,
	}
)

func (x ValveStatus) Enum() *ValveStatus {
	p := new(ValveStatus)
	*p = x
	return p
}

func (x ValveStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValveStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_valve_shared_proto_enumTypes[0].Descriptor()
}

func (ValveStatus) Type() protoreflect.EnumType {
	return &file_valve_shared_proto_enumTypes[0]
}

func (x ValveStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValveStatus.Descriptor instead.
func (ValveStatus) EnumDescriptor() ([]byte, []int) {
	return file_valve_shared_proto_rawDescGZIP(), []int{0}
}

var File_valve_shared_proto protoreflect.FileDescriptor

var file_valve_shared_proto_rawDesc = []byte{
	0x0a, 0x12, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2a, 0x7e, 0x0a, 0x0b,
	0x56, 0x61, 0x6c, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x11, 0x56,
	0x41, 0x4c, 0x56, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x56, 0x41, 0x4c, 0x56, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x56, 0x41, 0x4c, 0x56, 0x45, 0x5f, 0x4f,
	0x50, 0x45, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x56, 0x41, 0x4c, 0x56,
	0x45, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x56, 0x41, 0x4c, 0x56,
	0x45, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x56,
	0x41, 0x4c, 0x56, 0x45, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x05, 0x42, 0x38, 0x48, 0x03,
	0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46, 0x72, 0x61,
	0x6e, 0x63, 0x65, 0x73, 0x63, 0x6f, 0x49, 0x6c, 0x61, 0x72, 0x69, 0x6f, 0x2f, 0x67, 0x72, 0x6f,
	0x77, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x70, 0x62, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_valve_shared_proto_rawDescOnce sync.Once
	file_valve_shared_proto_rawDescData = file_valve_shared_proto_rawDesc
)

func file_valve_shared_proto_rawDescGZIP() []byte {
	file_valve_shared_proto_rawDescOnce.Do(func() {
		file_valve_shared_proto_rawDescData = protoimpl.X.CompressGZIP(file_valve_shared_proto_rawDescData)
	})
	return file_valve_shared_proto_rawDescData
}

var file_valve_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_valve_shared_proto_goTypes = []interface{}{
	(ValveStatus)(0), // 0: shared.ValveStatus
}
var file_valve_shared_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_valve_shared_proto_init() }
func file_valve_shared_proto_init() {
	if File_valve_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_valve_shared_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_valve_shared_proto_goTypes,
		DependencyIndexes: file_valve_shared_proto_depIdxs,
		EnumInfos:         file_valve_shared_proto_enumTypes,
	}.Build()
	File_valve_shared_proto = out.File
	file_valve_shared_proto_rawDesc = nil
	file_valve_shared_proto_goTypes = nil
	file_valve_shared_proto_depIdxs = nil
}
