// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shutter.proto

package shutterpb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ShutRequest) Validate() error {
	return nil
}
