version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: grower-scheduler-itest
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersecret
    networks:
      mongonet: {}

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecret
    networks: 
      mongonet: {}

  itest:
    build: 
      context: ../../../
      dockerfile: integration/Dockerfile
    
    environment: 
      MONGO_DATABASE: grower-scheduler-itest
      MONGO_USERNAME: root
      MONGO_PASSWORD: supersecret
      MONGO_CONNSTR: mongodb://mongo:27017
    networks:
      mongonet: {}
    working_dir: /app
    depends_on:
      - mongo
    # command: sleep infinity
    command: "go test ./internal/scheduler/mongostore -run Integration"

networks:
  mongonet: {}
