version: '3.8'
services:
  valvegrpc:
    build: 
      context: ../../
      dockerfile: build/docker/valvegrpc/server/Dockerfile
    environment: 
      VALVEGRPC_ADDRESS: "localhost:8080"
      VALVEGRPC_AMQP_CONNECTION_STRING: "amqp://guest:guest@rabbitmq:5672/"
      
  valveproc:
    build:
      context: ../../
      dockerfile: build/docker/valvecmdsproc/Dockerfile
    environment:
      VCMDSVR_POSITIVE_PIN: 10
      VCMDSVR_NEGATIVE_PIN: 4
      VCMDSVR_PULSE_LENGTH: 20ms
      VCMDSVR_AMQP_CONNECTION_STRING: "amqp://guest:guest@rabbitmq:5672/"

  scheduler:
    build: 
      context: ../../
      dockerfile: build/docker/scheduler/server/Dockerfile
    environment: 
      SCHEDULER_VALVE_CMDR_HOST: valvecmder
      SCHEDULER_ADDRESS: localhost:8080
  
  shutter:
    build:
      context: ../../
      dockerfile: build/docker/shutter/server/Dockerfile
    environment:
      SHUTTER_ADDRESS: localhost:8080
      SHUTTER_OUTPUT_PIN: 27

  prometheus:
    image: prom/